SECRET_KEY_BASE: xxx
PUA_CLIENT_ID: xxx
PUA_CLIENT_SECRET: xxx
VOICEBASE_CLIENT_ID: xxx
VOICEBASE_CLIENT_SECRET: xxx
PROJECT_ID: sample-project
NEW_RELIC_LICENSE_KEY: xxx
AWS_S3_ACCESS_KEY_ID: xxx
AWS_S3_SECRET_ACCESS_KEY: xxx

development:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
  AZUREAD_ENDPOINT_HOSTNAME: xxx
  AZUREAD_AAD_CLIENT_ID: xxx
  AZUREAD_AAD_TENANT: xxx

production:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
  AZUREAD_ENDPOINT_HOSTNAME: xxx
  AZUREAD_AAD_CLIENT_ID: xxx
  AZUREAD_AAD_TENANT: xxx
