SECRET_KEY_BASE: xxx
PUA_CLIENT_ID: xxx
PUA_CLIENT_SECRET: xxx
PROJECT_ID: sample-project
NEW_RELIC_LICENSE_KEY: xxx
development:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
production:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
